// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace NguyenTheAnh264.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20211006010607_NTA0264")]
    partial class NTA0264
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("MVCPerson.Models.PersonNTA264", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonName")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("PersonNTA264");
                });

            modelBuilder.Entity("NguyenTheAnh0264.Models.NTA0264", b =>
                {
                    b.Property<int>("NTAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NTAGender")
                        .HasColumnType("TEXT");

                    b.Property<string>("NTAName")
                        .HasColumnType("TEXT");

                    b.HasKey("NTAId");

                    b.ToTable("NTA0264");
                });
#pragma warning restore 612, 618
        }
    }
}
